###rotas de jogadores
### Criar player (OK, 201 created)
### Criar player (email duplicado -> 409 conflict)
### Criar player (body inválido -> 400 bad request)
POST http://localhost:3333/players
Content-Type: application/json

{
  "name": "Pedro",
  "email": "pedroteste@email.com"
}

### 

#listar jogadores
GET http://localhost:3333/players

### 

#pegar jogadores por id
GET http://localhost:3333/players/eabf0b97-b30e-4090-8fab-fe782e101858


### rotas de challenges

#cria uma challenge
POST http://localhost:3333/challenges
Content-Type: application/json

{
  "title": "Desafio da corrida",
  "description": "quem corre mais km",
  "start_date": "2026-01-02T10:00:00.000Z",
  "end_date": "2026-02-27T18:00:00.000Z"
}

###

#listar challenges
GET http://localhost:3333/challenges

### 

#buscar challenge por id
GET http://localhost:3333/challenges/53e4aa8b-6c8e-4169-97f5-cd88e8c6adc3


###rota de score


#criar um score
POST http://localhost:3333/scores
Content-Type: application/json

{
  "player_id": "eabf0b97-b30e-4090-8fab-fe782e101858",
  "challenge_id": "3ee16c02-4f66-44ff-9218-52c48e5e929c",
  "points": -1
}


###rota de ranking

#pontos totais dos jogadores em uma challenge
GET http://localhost:3333/challenges/3ee16c02-4f66-44ff-9218-52c48e5e929c/ranking

### best challenge por jogador
GET http://localhost:3333/players/eabf0b97-b30e-4090-8fab-fe782e101858/stats